services:
  frontend:
    build: ./frontend
    ports:
      - "8000":80" 
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
      - DATABASE_URL="${YOUR_KEY}"
      - DIRECT_URL="${YOUR_API_KEY}"